# Generated by Django 4.2.7 on 2023-11-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OSFUser",
            fields=[
                (
                    "user_guid",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "OSF User",
                "verbose_name_plural": "OSF Users",
            },
        ),
    ]
