# Generated by Django 4.2.7 on 2023-11-10 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('provider_name', models.CharField()),
            ],
            options={
                'verbose_name': 'Addon Provider',
                'verbose_name_plural': 'Addon Providers',
            },
        ),
        migrations.CreateModel(
            name='ExternalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('oauth_key', models.CharField(blank=True, null=True)),
                ('oauth_secret', models.CharField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, null=True)),
                ('date_last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'External Credentials',
                'verbose_name_plural': 'External Credentials',
            },
        ),
        migrations.CreateModel(
            name='InternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('resource_uri', models.URLField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'OSF Resource',
                'verbose_name_plural': 'OSF Resources',
            },
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('user_osf_uri', models.URLField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'OSF User',
                'verbose_name_plural': 'OSF Users',
            },
        ),
        migrations.CreateModel(
            name='StorageAddonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('service_name', models.CharField()),
                ('read_only', models.BooleanField()),
                ('supports_copy', models.BooleanField()),
                ('supports_user_specified_root_folder', models.BooleanField()),
                ('supports_file_versioning', models.BooleanField()),
                ('supports_bulk_download', models.BooleanField()),
                ('max_concurrent_downloads', models.IntegerField()),
                ('max_upload_mb', models.IntegerField()),
                ('auth_uri', models.URLField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.addonprovider')),
            ],
            options={
                'verbose_name': 'Storage Provider Settings',
                'verbose_name_plural': 'Storage Provider Settings',
            },
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('external_service_id', models.CharField()),
                ('external_service_display_name', models.CharField()),
                ('addon_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.addonprovider')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.externalcredentials')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.osfuser')),
            ],
            options={
                'verbose_name': 'External Account',
                'verbose_name_plural': 'External Accounts',
            },
        ),
        migrations.CreateModel(
            name='ConfiguredStorageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('root_folder', models.CharField()),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.externalaccount')),
                ('internal_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.osfresource')),
            ],
            options={
                'verbose_name': 'Configured Storage Addon',
                'verbose_name_plural': 'Configured Storage Addons',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedStorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('default_root_folder', models.CharField()),
                ('base_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addon_service.externalaccount')),
            ],
            options={
                'verbose_name': 'Authorized Storage Account',
                'verbose_name_plural': 'Authorized Storage Accounts',
            },
        ),
    ]
